### PR TITLE
Issues 28: Cache base method definition in pipeline manager.

### PR DESCRIPTION
**Pull request by hypercodeplace**
Description and discussion of the task is here: https://github.com/unitycontainer/interception/issues/28

### CODE REVIEW

**Comment by hypercodeplace** [comment]
Hey @ENikS , I notices that you have erased my commit https://github.com/unitycontainer/interception/commit/f0f1a1040eb3e501e90babb6558a14b1a53351b9 and now it appears in the repository as your commit https://github.com/unitycontainer/interception/commit/b38bce244257269a4c3f5021b4b8bdf694c792cb.
I just want to find out how it happened? I think it's not good to hide contributors of open source repositories.

**Comment by ENikS** [comment]
I have nothing to do with it, I don't have these powers. You might ask GitHub admins why the repo is `unknown`. Did you delete your repository or profile?

**Comment by hypercodeplace** [comment]
>why the repo is `unknown`

This is not a question about `unknown repository` repository, but about git history.

>Did you delete your repository or profile?

I deleted the fork as unnecessary, I have never deleted my profile.

>You might ask GitHub admins

@ENikS I think this is not a question of the GitHub administrators, but the fact that you, probably, did a force push or squash merge?

**Comment by ENikS** [comment]
I did a lot of refactoring lately and planing to do more in near feature. If your changes got squashed, it was not intentional but I am sorry nonetheless. 

Generally, I'd like to expand contributors list, not shrink it, so if you feel so inclined, you are welcome to resubmit and I would be more than happy to add these to the history.

**Comment by hypercodeplace** [comment]
@ENikS Thanks for your answer.

I understand that most likely this happened unintentionally. If you do not mind, I would like to restore the history.

> you are welcome to resubmit

Could you please explain what do you mean by "resubmit"?

**Comment by ENikS** [comment]
Sent another pr.

**Comment by hypercodeplace** [comment]
But if all changes are already in master, there will be no any changes in another PR?

**Comment by ENikS** [comment]
Alexey,

I am a bit sick at the moment so...
You're smart boy, figure something out ;)

**Comment by hypercodeplace** [comment]
@ENikS Ok, thank you, Eugene, will do something.
And I wish you a speedy recovery! 💪🤜🦠

**Pull request merged**
